using System;
namespace URHO2D.Template
{
	// Perhaps this file can be auto-generated by T4 script
	public static class Assets
	{
		public static class Materials
		{
			public const string Enemy1 = "Materials/Monkey.xml";
			public const string Enemy2 = "Materials/Enemy4DD.xml";
			public const string Enemy3 = "Materials/Enemy3.xml";
			public const string SmallPlate = "Materials/Enemy3weapon.xml";
			public const string Pyramid = "Materials/PyramidMaterial.xml";
			public const string Grass = "Materials/Grass.xml";
			public const string Player = "Materials/Player1D.xml";
			public const string Apple = "Materials/Apple.xml";
			public const string MachineGun = "Materials/MachineGun.xml";
		}

		public static class Models
		{
			public const string Tree = "Models/PyramidTree.mdl";
			public const string Box = "Models/Box.mdl";
			public const string Plane = "Models/Plane.mdl";
			public const string Player = "Models/Player1.mdl";
			public const string Enemy1 = "Models/Monkey.mdl";
			public const string Enemy2 = "Models/Enemy4.mdl";
			public const string Enemy3 = "Models/Enemy3.mdl";
			public const string SmallPlate = "Models/Enemy3weapon.mdl";
			public const string Coin = "Models/Apple.mdl";
		}

		public static class Particles
		{
			public const string Explosion = "Particles/Explosion.pex";
			public const string PlayerExplosion = "Particles/PlayerExplosion.pex";
			public const string HeavyMissileExplosion = "Particles/HeavyMissileExplosion.pex";
			public const string MissileTrace = "Particles/MissileTrace.pex";
		}

		public static class Sounds
		{
			public const string BigExplosion = "Sounds/BigExplosion.wav";
			public const string MachineGun = "Sounds/MachineGun.wav";
			public const string SmallExplosion = "Sounds/SmallExplosion.wav";
			public const string Powerup = "Sounds/Powerup.wav";
		}

		public static class Fonts
		{
			public const string Font = "Fonts/Anonymous Pro.ttf";
		}

		public static class PostProcess
		{
			public const string FXAA3 = "PostProcess/FXAA3.xml";
		}

		public static class Textures
		{
			public const string XamarinLogo = "Textures/xamarin.png";
		}
		public static class Sprites
		{
			public const string Box = "Sprites/Box.png";
			public const string Ball = "Sprites/Ball.png";
            public const string Cog = "Sprites/Cog.png";
            public const string UrhoIcon = "Sprites/UrhoIcon.png";
            public const string Lev1_BG = "Sprites/Lev1_BG.png";
            public const string Level05 = "Sprites/Level05.png";

		}
		public static class SpriteShapes
		{
			public const string UrhoIcon = "Terrain.UrhoIcon.plist";
		}
		public static class Terrain
		{
			public const string tShapes = "Terrain.shapes.svg";
            public const string Level01 = "Terrain.Level01.svg";
            public const string Level02 = "Terrain.Level02.svg";
            public const string Level03 = "Terrain.Level03.svg";
            public const string Level04 = "Terrain.Level04.svg";
            public const string Level05 = "Terrain.Level05.svg";
            public const string Level06 = "Terrain.Level06.svg";
		}
	}
}
